version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          apk add docker-cli jq
          sh ruler.sh | tee ruler.txt
      - store_artifacts:
          path: ruler.txt
          destination: ruler.txt